name=FauxmoESP
version=3.4
author=Paul Vint <paul@vintlabs.com>, Claudiu Ivan <klaudyu@gmail.com>
maintainer=Claudiu Ivan <klaudyu@gmail.com>
sentence=Amazon Alexa support for ESP8266, ESP32 and Raspberry Pi Pico W, integration in Home Assistant
paragraph=
category=Communication
url=https://github.com/klaudyu/fauxmoESP
architectures=esp8266,esp32,rp2040
includes=fauxmoESP.h
